### PR TITLE
reproduced b213df3

### PR DESCRIPTION
**Pull request by git-afsantos**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
The version of ROS you've reproduced the bug in.

So if you built an image for Kinetic, you would put `kinetic` there.

**Comment by git-afsantos** [comment]
Oh, it is simple, then. I asked because I happened to open `b166c93.bug`, which contains

```yaml
    rosdistro: ros/rosdistro@d0e0b0bfa624b65e40c81a6b308b84cf54f73ba7
```

This got me confused, and I immediately assumed I was missing something.

**Comment by gavanderhoorn** [comment]
> Oh, it is simple, then. I asked because I happened to open `b166c93.bug`, which contains
> 
> ```yaml
>     rosdistro: ros/rosdistro@d0e0b0bfa624b65e40c81a6b308b84cf54f73ba7
> ```
> 
> This got me confused, and I immediately assumed I was missing something.

O wait, my apologies.

That is indeed what that field is for. Not the name of the rosdistro.

**Comment by git-afsantos** [comment]
> That is indeed what that field is for. Not the name of the rosdistro.

Where does that hash come from, then? Is it time machine related?

**Comment by git-afsantos** [comment]
Just noticed the taxonomy file is updated with the description of those fields.

```yaml
reproduction-images:
	buggy: the nearest compiling commit in git log that exhibits the bug (an anecstor of the fixing commit)
	fixed: the neaerst compiling commit that contains the fix (a child of the fixing commit)
	rosdistro: the rosdistro commit capturing the distribution packages used in building the reproduction image.
	note: Any notes about how you reproduced the bug in your L3 test case.  The idea is to help the reader analyze the test (the main idea should be here).  For instance: I inserted an assertion to enforce X at a point B, and then modified a launch file to provide the input that drives it there.  Or since the bug was flaky and hard to reproduce, we first determinized the control flow, and then ...

N/A if the bug not reproduced.
```

This means that I have a bunch of bug files to fix. I should open a new issue to make sure I remember that in the future.

**Comment by gavanderhoorn** [comment]
> > That is indeed what that field is for. Not the name of the rosdistro.
> 
> Where does that hash come from, then? Is it time machine related?

It is the commit at which `ros/rosdistro` was checked out by the time machine for the timestamp you've provided it.

This is printed by the time machine when it's generating your `.rosinstall` file. An example:

```
Reverting to ros/rosdistro@2b0f84cf
```

**Pull request merged**
