### PR TITLE
introduce SOFTWARE:NETWORK label

### PR DESCRIPTION
**Pull request by ipa-hsd**
As discussed in https://github.com/robust-rosin/robust/issues/415, some bugs report communication failures, which do not fit into `SOFTWARE:LIVENESS`.

### CODE REVIEW

**Comment by wasowski** [comment]
I checked all entries, and I confirm all changes to SOFTWARE:NETWORK (even though for many software people this would be `SYSTEM:NETWORK` - but it is really hard to draw the line).  One case is different:
*  `geometry2/245b02b/245b02b.bug` gets `SYSTEM:LOSS-OF-FUNCTIONALITY`, which sounds fine -- I just do not remember what are the current label names (whether this one is up-to-date).  For what it's worth, this code is defined in the YML schema file.
I am ready to merge this during the meeting tonight.

**Comment by ipa-hsd** [comment]
> geometry2/245b02b/245b02b.bug gets SYSTEM:LOSS-OF-FUNCTIONALITY

@wasowski thanks for the catch. It should be part of https://github.com/robust-rosin/robust/pull/430

**Comment by wasowski** [comment]
Let's keep it and merge it here, if we agree that this is correct. Moving hunks between PRs will be more pain than needed.

**Comment by wasowski** [comment]
@ipa-hsd you need to merge this, because I cannot rebase in your repo (I suppose that I cannot push into your fork).

**Pull request merged**
