### PR TITLE
Added support for multiple PUTs (assuming a single fork)

### PR DESCRIPTION
**Pull request by ChrisTimperley**
Should address current issues with #262.

### CODE REVIEW

**Comment by ipa-hsd** [comment]
(Had errors while building the Docker image, but I guess that is unrelated to this PR)

Built the manifest successfully with this PR :+1:

**Comment by ipa-hsd** [comment]
The resultant `robust.bugzoo.yml` looks like this:
```
- arguments:
    CATKIN_PACKAGES: c;o;b;_;a;n;d;r;o;i;d;_;m;s;g;s; ;c;o;b;_;a;n;d;r;o;i;d;_;s;c;r;i;p;t;_;s;e;r;v;e;r
    IS_BUILD_FAILURE: 'no'
    REPO_BUG_COMMIT: 21126f5e3d2e15ae8c93705dc3e8e999707da48e
    REPO_FIX_COMMIT: 79867c88acc64342f061e6324ed6b84ca7e0773d
    REPO_FORK_URL: https://github.com/robust-rosin/cob_android
    ROS_DISTRO: indigo
    UBUNTU_VERSION: 14.04.5
    USE_APT_OLD_RELEASES: false
    USE_OSRF_REPOS: false
  context: care-o-bot/79867c8
  file: Dockerfile
  tag: robustrosin/robust:79867c8
```

**Comment by ChrisTimperley** [comment]
@ipa-hsd Would you mind trying to build the image for #262 using the latest version of the PR?

**Comment by ipa-hsd** [comment]
@ChrisTimperley I was already able to build the image (guess I was unclear in my last post :) )

**Comment by ipa-hsd** [comment]
@ChrisTimperley  I am able to build the image now. Please see https://github.com/robust-rosin/robust/issues/262#issuecomment-479435314

**Comment by ChrisTimperley** [comment]
> @ChrisTimperley I am able to build the image now. Please see [#262 (comment)](https://github.com/robust-rosin/robust/issues/262#issuecomment-479435314)

Sorry, I don't think I was clear. I've changed the `Dockerfile` to build the PUTs via `catkin_make --only-pkg-with-deps`, rather than `catkin build` or `catkin_make -DCMAKE_WHITELIST_PACKAGES=...`. Just to confirm, have you tried to build the image with the most recent version of the `Dockerfile` in this PR?

**Comment by ipa-hsd** [comment]
Yes, I rebased the new changes from this PR on the latest `master`. I can build the image successfully now.

**Pull request merged**
