### PR TITLE
Fixed issue in Dockerfile that caused build to fail when checking out bug/fix commits

### PR DESCRIPTION
**Pull request by ChrisTimperley**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Can we get some context here?

`git pull` can potentially pop up a merge commit dialog. Not something we'd want.

What made the build fail with the `fetch`es?

**Comment by ChrisTimperley** [comment]
> Can we get some context here?
> 
> `git pull` can potentially pop up a merge commit dialog. Not something we'd want.

Ah, fair point.

> 
> What made the build fail with the `fetch`es?

`git` would complain that the commit doesn't exist (`"Couldn't find remote ref ......"`).

**Comment by gavanderhoorn** [comment]
Does `git fetch origin "${REPO_FIX_COMMIT}"` actually make sense?

Don't we want the complete history, including the fix and bad commit?

Fetching a single commit is actually supported with `git`, but I'm not sure that is what we want to do here.

**Comment by gavanderhoorn** [comment]
> > Does `git fetch origin "${REPO_FIX_COMMIT}"` actually make sense?
> > Don't we want the complete history, including the fix and bad commit?
> > Fetching a single commit is actually supported with `git`, but I'm not sure that is what we want to do here.
> 
> I think you're right. I've switched the command to `git fetch origin`, although I'm unsure that `fetch origin` will fetch commits from remote branches that don't exist locally?

Not sure either, but if we want to be sure we could explicitly `fetch` those branches?

Or do we not know on which branches those commits live?

**Comment by gavanderhoorn** [comment]
Apparently we could use `git fetch --unshallow`:

> If the source repository is complete, convert a shallow repository to a complete one, removing all the limitations imposed by shallow repositories.
> 
> If the source repository is shallow, fetch as much as possible so that the current repository has the same history as the source repository.

**Comment by ChrisTimperley** [comment]
Fixed via:
```
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git fetch --all
```

See: https://stackoverflow.com/questions/6802145/how-to-convert-a-git-shallow-clone-to-a-full-clone

**Comment by ChrisTimperley** [comment]
@git-afsantos can you confirm that this works for you?

**Comment by git-afsantos** [comment]
@ChrisTimperley it seems to have worked for the bug I have stuck on this issue. It advanced in the build, and I am now getting another unrelated issue.

**Pull request merged**
