### PR TITLE
Reads gdocs and adds fault and falure codes to bugs

### PR DESCRIPTION
**Pull request by ipa-hsd**
cleaned up version of https://github.com/robust-rosin/robust/pull/385

### CODE REVIEW

**Comment by ipa-hsd** [comment]
@ChrisTimperley can we please merge this soon if it looks fine?

**Comment by ChrisTimperley** [comment]
What's the difference between this PR and https://github.com/robust-rosin/robust/pull/385?

**Review by ChrisTimperley — APPROVED** [review]
👍🏻 Let's go ahead and merge it

**Comment by ipa-hsd** [comment]
> What's the difference between this PR and #385?

Just improved the commits and I am not sure why the rebased commits were not getting pushed to https://github.com/robust-rosin/robust/pull/385.

**Pull request merged**
