### PR TITLE
[WIP] Fix turtlebot

### PR DESCRIPTION
**Pull request by ipa-hsd**
Currently added only fault and failure codes. This PR is behind https://github.com/robust-rosin/robust/pull/377

### CODE REVIEW

**Comment by ChrisTimperley** [comment]
Did you write a script to pull codes from the spreadsheet or were these added manually?

**Comment by ipa-hsd** [comment]
> Did you write a script to pull codes from the spreadsheet or were these added manually?

Added manually

**Comment by ChrisTimperley** [comment]
Since it's very likely that the spreadsheet will change, we'll want to add these codes instead.

**Comment by ipa-hsd** [comment]
Noted.

**Comment by ipa-hsd** [comment]
closing for https://github.com/robust-rosin/robust/pull/391

**Pull request closed without merging**
