### PR TITLE
Added (empty) Python library for interacting with ROBUST

### PR DESCRIPTION
**Pull request by ChrisTimperley**
Having a proper Python library for interacting with the ROBUST dataset makes it a lot easier to write good Jupyter notebooks (and to write useful scripts that rely on common functionality). This PR creates a `robust` package inside the `lib` directory and adds a reasonable `tox` linting setup into the CI (i.e., `flake8` and `mypy`).

### CODE REVIEW

**Comment by wasowski** [comment]
This is a great initiative.  I think we should merge ASAP (that is as soon as @gavanderhoorn approves :) )

**Comment by ChrisTimperley** [comment]
This was a hard but valuable lesson in rebasing vs. merging on feature branches. I managed to resolve the situation via the following:

```
$ git reset --hard 35ba39b
$ git rebase master
```

The first command rolls back the commit history to the point before the `git merge master` occurred. This is fine since there were no changes beyond that point anyway. The subsequent commit then performs the actual rebase.

@wasowski We should be good to merge?

**Comment by ChrisTimperley** [comment]
(Note that I'm still in favour of squashing and merging the PR before going into master. I can squash locally, but that would destroy the commit history on this PR, whereas using GitHub's "squash and merge" retains it.)

**Comment by wasowski** [comment]
squashed and merged!

**Pull request merged**
