### PR TITLE
universal_robot f8d175b

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
If someone could try to build this on their local BugZoo installation, that would be nice.

**Comment by gavanderhoorn** [comment]
This now uses the same layout as #49.

**Comment by ChrisTimperley** [comment]
```
Step 34/39 : RUN cd src/repo-under-test  && echo "[ROBUST] fetching fixed and buggy source code..."  && echo "[ROBUST] using fix commit: ${REPO_FIX_COMMIT}"  && echo "[ROBUST] using bug commit: ${REPO_BUG_COMMIT}"  && git fetch origin "${REPO_FIX_COMMIT}"  && git fetch origin "${REPO_BUG_COMMIT}"  && git checkout "${REPO_BUG_COMMIT}"  && echo "[ROBUST] fetched fixed and buggy source code."

 ---> Running in ad72b313b6bd
[ROBUST] fetching fixed and buggy source code...
[ROBUST] using fix commit: 8f7f2418edc1d507853c1c766b6a79123393007b
[ROBUST] using bug commit: 2cb16836ab3a14e3c534d2d20837642e3cc4a210
From https://github.com/robust-rosin/universal_robot
 * branch            8f7f2418edc1d507853c1c766b6a79123393007b -> FETCH_HEAD

From https://github.com/robust-rosin/universal_robot
 * branch            2cb16836ab3a14e3c534d2d20837642e3cc4a210 -> FETCH_HEAD

Note: checking out '2cb16836ab3a14e3c534d2d20837642e3cc4a210'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 2cb1683... Merge pull request #253 from Jntzko/prefixInLaunch

[ROBUST] fetched fixed and buggy source code.
Removing intermediate container ad72b313b6bd
 ---> f8682e126736
Step 35/39 : RUN echo "#!/bin/bash\npushd '${ROS_WSPACE}/src/repo-under-test' && \ngit clean -dfx && \ngit checkout \"\$1\" && \necho \"switched mode to: \$1\"" > switch  && echo "#!/bin/bash\n'${ROS_WSPACE}/switch' \"\${REPO_FIX_COMMIT}\"" > fix  && echo "#!/bin/bash\n'${ROS_WSPACE}/switch' \"\${REPO_BUG_COMMIT}\"" > unfix  && chmod +x fix unfix switch

 ---> Running in afc951fb75ee
Removing intermediate container afc951fb75ee
 ---> 571e11122e1a
Step 36/39 : RUN echo "[ROBUST] creating build script"  && echo "[ROBUST] PUT is provided by catkin package: '${CATKIN_PKG}'"  && echo "#!/bin/bash\n          source /opt/ros/$ROS_DISTRO/setup.bash           && catkin_make --only-pkg-with-deps=${CATKIN_PKG}" > build.sh  && chmod +x build.sh  && echo "[ROBUST] created build script"

 ---> Running in ec9570b7fbfb
[ROBUST] creating build script
[ROBUST] PUT is provided by catkin package: 'ur_kinematics'
[ROBUST] created build script
Removing intermediate container ec9570b7fbfb
 ---> 85f603b806ff
Step 37/39 : RUN echo "[ROBUST] attempting to build PUT..."  && echo "[ROBUST] is a build failure expected? ${IS_BUILD_FAILURE}."  && ./build.sh || [ "${IS_BUILD_FAILURE}" = "yes" ]

 ---> Running in e991217a75cf
[ROBUST] attempting to build PUT...
[ROBUST] is a build failure expected? yes.
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /ros_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.6")
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /ros_ws/build/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- BUILD_SHARED_LIBS is on
-- Using CATKIN_WHITELIST_PACKAGES: ur_kinematics
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - ur_kinematics
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'ur_kinematics'
-- ==> add_subdirectory(repo-under-test/ur_kinematics)
-- Using these message generators: gencpp;genlisp;genpy
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /ros_ws/build
Scanning dependencies of target ur3_kin
Scanning dependencies of target ur10_kin
Scanning dependencies of target ur5_kin
[ 16%]
[ 33%]
[ 50%]
Building CXX object repo-under-test/ur_kinematics/CMakeFiles/ur3_kin.dir/src/ur_kin.cpp.o
Building CXX object repo-under-test/ur_kinematics/CMakeFiles/ur10_kin.dir/src/ur_kin.cpp.o
Building CXX object repo-under-test/ur_kinematics/CMakeFiles/ur5_kin.dir/src/ur_kin.cpp.o
Linking CXX shared library /ros_ws/devel/lib/libur10_kin.so
[ 50%]
Built target ur10_kin
Scanning dependencies of target ur10_moveit_plugin
[ 66%]
Building CXX object repo-under-test/ur_kinematics/CMakeFiles/ur10_moveit_plugin.dir/src/ur_moveit_plugin.cpp.o
Linking CXX shared library /ros_ws/devel/lib/libur3_kin.so
Linking CXX shared library /ros_ws/devel/lib/libur5_kin.so
[ 66%]
Built target ur3_kin
[ 66%]
Built target ur5_kin
Scanning dependencies of target ur3_moveit_plugin
[ 83%]
Building CXX object repo-under-test/ur_kinematics/CMakeFiles/ur3_moveit_plugin.dir/src/ur_moveit_plugin.cpp.o
Scanning dependencies of target ur5_moveit_plugin
[100%]
Building CXX object repo-under-test/ur_kinematics/CMakeFiles/ur5_moveit_plugin.dir/src/ur_moveit_plugin.cpp.o
In file included from /ros_ws/src/repo-under-test/ur_kinematics/src/ur_moveit_plugin.cpp:88:0:
/ros_ws/src/repo-under-test/ur_kinematics/include/ur_kinematics/ur_moveit_plugin.h:97:74: fatal error: moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp: No such file or directory
 #include <moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp>
                                                                          ^
compilation terminated.

In file included from /ros_ws/src/repo-under-test/ur_kinematics/src/ur_moveit_plugin.cpp:88:0:
/ros_ws/src/repo-under-test/ur_kinematics/include/ur_kinematics/ur_moveit_plugin.h:97:74: fatal error: moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp: No such file or directory
 #include <moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp>
                                                                          ^
compilation terminated.

In file included from /ros_ws/src/repo-under-test/ur_kinematics/src/ur_moveit_plugin.cpp:88:0:
/ros_ws/src/repo-under-test/ur_kinematics/include/ur_kinematics/ur_moveit_plugin.h:97:74: fatal error: moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp: No such file or directory
 #include <moveit/kdl_kinematics_plugin/chainiksolver_pos_nr_jl_mimic.hpp>
                                                                          ^

compilation terminated.

make[2]: *** [repo-under-test/ur_kinematics/CMakeFiles/ur3_moveit_plugin.dir/src/ur_moveit_plugin.cpp.o] Error 1

make[1]: *** [repo-under-test/ur_kinematics/CMakeFiles/ur3_moveit_plugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

make[2]: *** [repo-under-test/ur_kinematics/CMakeFiles/ur5_moveit_plugin.dir/src/ur_moveit_plugin.cpp.o] Error 1

make[1]: *** [repo-under-test/ur_kinematics/CMakeFiles/ur5_moveit_plugin.dir/all] Error 2

make[2]: *** [repo-under-test/ur_kinematics/CMakeFiles/ur10_moveit_plugin.dir/src/ur_moveit_plugin.cpp.o] Error 1

make[1]: *** [repo-under-test/ur_kinematics/CMakeFiles/ur10_moveit_plugin.dir/all] Error 2

make: *** [all] Error 2

Base path: /ros_ws
Source space: /ros_ws/src
Build space: /ros_ws/build
Devel space: /ros_ws/devel
Install space: /ros_ws/install
Creating symlink "/ros_ws/src/CMakeLists.txt" pointing to "/opt/ros/indigo/share/catkin/cmake/toplevel.cmake"
Whitelisted packages: ur_kinematics
####
#### Running command: "cmake /ros_ws/src -DCATKIN_DEVEL_PREFIX=/ros_ws/devel -DCMAKE_INSTALL_PREFIX=/ros_ws/install -DCATKIN_WHITELIST_PACKAGES=ur_kinematics -G Unix Makefiles" in "/ros_ws/build"
####
####
#### Running command: "make -j4 -l4" in "/ros_ws/build"
####
zZ
Invoking "make -j4 -l4" failed

Removing intermediate container e991217a75cf
 ---> a60eabc234fa
Step 38/39 : COPY test.sh .

 ---> 363734a22c79
Step 39/39 : RUN cd src/repo-under-test  && git diff "${REPO_BUG_COMMIT}" "${REPO_FIX_COMMIT}" > "${ROS_WSPACE}/fix.patch"

 ---> Running in 0f9999556c50
Removing intermediate container 0f9999556c50
 ---> 434668202043
Successfully built 434668202043
Successfully tagged robustrosin/robust:f8d175b
Built image: robustrosin/robust:f8d175b
```

**Comment by ChrisTimperley** [comment]
Looks good. Go ahead and merge when you're ready :+1:

**Comment by gavanderhoorn** [comment]
The only thing I realise I didn't do was adding branches to `robust-rosin/universal_robot` for this bug.

I'm not sure what we agreed upon again. @wasowski ?

Are they still needed?

**Comment by gavanderhoorn** [comment]
I can add the branches later.

Still not entirely sure any more what we decided.

**Comment by wasowski** [comment]
We still need the branches  because we need to write tests (and we need version control for that).  I noticed that Andre creates bugname_robust_buggy and bugname_robust_fixed. I try to follow this convention, and even might have updated the doc. With the direct use of hashes in the manifest file I don't think we need release tags though.

**Pull request merged**
