### PR TITLE
Initial Travis config with yamllint

### PR DESCRIPTION
**Pull request by gavanderhoorn**
For #153.

No JSON schema checking though.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
This currently fails, as some of the `.bug` files contain markup that `yamllint` doesn't like.

**Comment by ChrisTimperley** [comment]
> Fixed minor whitespace issues, build now passing.
> 
> Current yamllint config reduces level of "too long line" notices to `warn`.
> 
> Other than that it's the standard config.
> 
> We might want to consider enabling/enforcing (ie: strict) some of the [other rules](https://yamllint.readthedocs.io/en/stable/rules.html) (for instance: [truthy](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy)).

`truthy` looks useful, and maybe `empty-values` and `key-duplicates` too?

**Comment by gavanderhoorn** [comment]
> This looks great. Maybe we could add `truthy`, `empty-values` and `key-duplicates`?

sure.

I'll merge this PR first, as it introduces the initial config.

Feel free to update the configuration afterwards with more rules.

Be warned that you may have to fixup the `.bug` files as well then though :)

**Comment by ChrisTimperley** [comment]
I'm good with making it a warning.

What do you think to omitting the `trace` property from those documents?

**Comment by gavanderhoorn** [comment]
Tbh I can't really remember what `trace` was for. Perhaps @wasowski can provide some input here?

**Comment by git-afsantos** [comment]
I think `trace` was used to insert stack traces and such, when the bug is a runtime bug. At least, that is what I understood, and what I have used it for.

**Comment by git-afsantos** [comment]
https://github.com/robust-rosin/robust/blob/f6db508125eb2a583841a58c87d98c165456a7c0/doc/taxonomy-description.txt#L126

**Comment by gavanderhoorn** [comment]
Ah, ok. I remember now, yes.

So empty values would not be acceptable in any case.

Then we could keep the linter config as `error`.

**Pull request merged**
